# Generated by Django 2.2.17 on 2020-12-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.User')),
            ],
        ),
    ]
