# Generated by Django 2.2.17 on 2020-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account_name',
            field=models.CharField(max_length=150),
        ),
    ]
