# Generated by Django 2.2.17 on 2020-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20201230_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
