# Generated by Django 2.2.17 on 2020-12-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_auto_20201230_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
    ]
